name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      distTag:
        description: 'NPM tag (e.g. use "next --canary" to release a test version, add "--force-publish" to release all packages)'
        required: true
        default: 'latest'

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

permissions: {}
jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.1.7
        with:
          route: GET /orgs/:organisation/teams/:team/memberships/${{ github.actor }}
          team: technical-steering-committee
          organisation: webdriverio
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  release:
    permissions:
      contents: write
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: NPM Setup
        run: |
          npm set registry "https://registry.npmjs.org/"
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm whoami
      - name: Git Setup
        run: |
          git config --global user.email "bot@webdriver.io"
          git config --global user.name "WebdriverIO Release Bot"
      - name: Install Dependencies
        run: npm ci
      - name: Release
        run: |
          npx runme run setup-full --chdir docs --filename Setup.md
          npx runme run generateTypings --chdir docs --filename Setup.md
          npx runme run publish --chdir docs --filename Release.md
          npx runme run pushReleaseTag --chdir docs --filename Release.md
        env:
          NODE_ENV: production
          RUNME_EXPERIMENTAL_CLI: true
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
